//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TabletPassCode
    {
        public int TabletPassCodeId { get; set; }
        public string TabletId { get; set; }
        public string MACAddress { get; set; }
        public string PassCode { get; set; }
        public Nullable<int> GrowerId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblGrower tblGrower { get; set; }
    }
}
