//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        public int AssetId { get; set; }
        public string AssetName { get; set; }
        public string Asset_ID { get; set; }
        public string AssetDesc { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
