//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditStatu
    {
        public tblAuditStatu()
        {
            this.tblAudits = new HashSet<tblAudit>();
            this.tblAudits1 = new HashSet<tblAudit>();
        }
    
        public int Status_Id { get; set; }
        public string Status { get; set; }
        public string CorrectiveActionStatus { get; set; }
    
        public virtual ICollection<tblAudit> tblAudits { get; set; }
        public virtual ICollection<tblAudit> tblAudits1 { get; set; }
    }
}
