//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAudit
    {
        public tblAudit()
        {
            this.tblAuditComments = new HashSet<tblAuditComment>();
            this.tblAuditComments1 = new HashSet<tblAuditComment>();
            this.tblCorrectiveActions = new HashSet<tblCorrectiveAction>();
        }
    
        public int Audit_Id { get; set; }
        public string AuditName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModifiled { get; set; }
        public int ChecklistID { get; set; }
        public int UserID { get; set; }
        public int GrowerId { get; set; }
        public int LocationId { get; set; }
        public int StatusId { get; set; }
        public bool IsActive { get; set; }
        public string TabletAuditId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> InspstatusId { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<tblAuditComment> tblAuditComments { get; set; }
        public virtual ICollection<tblAuditComment> tblAuditComments1 { get; set; }
        public virtual tblAuditStatu tblAuditStatu { get; set; }
        public virtual tblAuditStatu tblAuditStatu1 { get; set; }
        public virtual tblCheckList tblCheckList { get; set; }
        public virtual tblGrower tblGrower { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblCorrectiveAction> tblCorrectiveActions { get; set; }
    }
}
