//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditComment
    {
        public int AnsId { get; set; }
        public int AuditId { get; set; }
        public int QuestionId { get; set; }
        public int ChecklistId { get; set; }
        public string FieldNotes { get; set; }
        public string Answer { get; set; }
        public string GivenScore { get; set; }
        public string PossibleScore { get; set; }
        public string Comments { get; set; }
    
        public virtual tblAudit tblAudit { get; set; }
        public virtual tblAudit tblAudit1 { get; set; }
        public virtual tblCheckList tblCheckList { get; set; }
        public virtual tblCheckList tblCheckList1 { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblQuestion tblQuestion1 { get; set; }
    }
}
