//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorrectiveAction
    {
        public tblCorrectiveAction()
        {
            this.tblNonUsers = new HashSet<tblNonUser>();
        }
    
        public int RecordId { get; set; }
        public string CorrectiveAction { get; set; }
        public int AuditId { get; set; }
        public int QuestionId { get; set; }
        public int ChecklistId { get; set; }
        public int LocationId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> CompletedByDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public string RootCause { get; set; }
        public string ResultingAction { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string VerifiedName { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string NonUser { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CorrectiveActionStatus { get; set; }
        public Nullable<int> CorrectiveActionRevisionStatus { get; set; }
    
        public virtual tblAudit tblAudit { get; set; }
        public virtual tblCheckList tblCheckList { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblNonUser> tblNonUsers { get; set; }
    }
}
