//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChklstCntrlType
    {
        public int RecordId { get; set; }
        public int ControlCnt { get; set; }
        public int ControlId { get; set; }
        public string Inputs { get; set; }
        public int ChecklistId { get; set; }
        public int QuestionId { get; set; }
    
        public virtual tblCheckList tblCheckList { get; set; }
        public virtual tblControl tblControl { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
    }
}
