//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCheckList
    {
        public tblCheckList()
        {
            this.tblAuditComments = new HashSet<tblAuditComment>();
            this.tblAuditComments1 = new HashSet<tblAuditComment>();
            this.tblAudits = new HashSet<tblAudit>();
            this.tblChklstCntrlTypes = new HashSet<tblChklstCntrlType>();
            this.tblCorrectiveActions = new HashSet<tblCorrectiveAction>();
            this.tblQuestions = new HashSet<tblQuestion>();
        }
    
        public int ChecklistID { get; set; }
        public string CheckListName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<int> GrowerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int ChecklistStatus { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<tblAuditComment> tblAuditComments { get; set; }
        public virtual ICollection<tblAuditComment> tblAuditComments1 { get; set; }
        public virtual ICollection<tblAudit> tblAudits { get; set; }
        public virtual tblGrower tblGrower { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblChklstCntrlType> tblChklstCntrlTypes { get; set; }
        public virtual ICollection<tblCorrectiveAction> tblCorrectiveActions { get; set; }
        public virtual ICollection<tblQuestion> tblQuestions { get; set; }
    }
}
