//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupHeader
    {
        public tblGroupHeader()
        {
            this.tblQuestions = new HashSet<tblQuestion>();
        }
    
        public int GroupHeaderId { get; set; }
        public string GroupHeaderName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> GrowerID { get; set; }
    
        public virtual tblGrower tblGrower { get; set; }
        public virtual ICollection<tblQuestion> tblQuestions { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
