//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrower
    {
        public tblGrower()
        {
            this.tbl_TabletPassCode = new HashSet<tbl_TabletPassCode>();
            this.tblAssignedCompanies = new HashSet<tblAssignedCompany>();
            this.tblAudits = new HashSet<tblAudit>();
            this.tblCheckLists = new HashSet<tblCheckList>();
            this.tblGroupHeaders = new HashSet<tblGroupHeader>();
            this.tblLocations = new HashSet<tblLocation>();
        }
    
        public int GrowerId { get; set; }
        public string GrowerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CompanyPhone { get; set; }
        public string PhoneNumber { get; set; }
        public string ClientContact { get; set; }
        public string EmailAddress { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModyfiedBy { get; set; }
        public Nullable<System.DateTime> ModyfiedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<tbl_TabletPassCode> tbl_TabletPassCode { get; set; }
        public virtual ICollection<tblAssignedCompany> tblAssignedCompanies { get; set; }
        public virtual ICollection<tblAudit> tblAudits { get; set; }
        public virtual ICollection<tblCheckList> tblCheckLists { get; set; }
        public virtual ICollection<tblGroupHeader> tblGroupHeaders { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblLocation> tblLocations { get; set; }
    }
}
