//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int ImageId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> AuditId { get; set; }
        public Nullable<int> CorrectiveActonID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual tblQuestion tblQuestion { get; set; }
    }
}
