//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        public tblLocation()
        {
            this.tblAudits = new HashSet<tblAudit>();
            this.tblCorrectiveActions = new HashSet<tblCorrectiveAction>();
        }
    
        public int Location_Id { get; set; }
        public string Vision { get; set; }
        public string Location_Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Location_Desc { get; set; }
        public int GrowerId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tblAudit> tblAudits { get; set; }
        public virtual ICollection<tblCorrectiveAction> tblCorrectiveActions { get; set; }
        public virtual tblGrower tblGrower { get; set; }
    }
}
