//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNonUser
    {
        public int RecordId { get; set; }
        public int NonUserId { get; set; }
        public string NonUser { get; set; }
    
        public virtual tblCorrectiveAction tblCorrectiveAction { get; set; }
    }
}
