//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportType
    {
        public int ReportTypeID { get; set; }
        public string ReportType { get; set; }
        public string ReportDescription { get; set; }
        public bool Status { get; set; }
    }
}
