//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblAssets = new HashSet<tblAsset>();
            this.tblAssignedCompanies = new HashSet<tblAssignedCompany>();
            this.tblAudits = new HashSet<tblAudit>();
            this.tblCategories = new HashSet<tblCategory>();
            this.tblCheckLists = new HashSet<tblCheckList>();
            this.tblCorrectiveActions = new HashSet<tblCorrectiveAction>();
            this.tblGroupHeaders = new HashSet<tblGroupHeader>();
            this.tblGrowers = new HashSet<tblGrower>();
            this.tblRoles = new HashSet<tblRole>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public Nullable<System.DateTime> Datemodified { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<int> RoleId { get; set; }
        public bool ForgetPassword { get; set; }
    
        public virtual ICollection<tblAsset> tblAssets { get; set; }
        public virtual ICollection<tblAssignedCompany> tblAssignedCompanies { get; set; }
        public virtual ICollection<tblAudit> tblAudits { get; set; }
        public virtual ICollection<tblCategory> tblCategories { get; set; }
        public virtual ICollection<tblCheckList> tblCheckLists { get; set; }
        public virtual ICollection<tblCorrectiveAction> tblCorrectiveActions { get; set; }
        public virtual ICollection<tblGroupHeader> tblGroupHeaders { get; set; }
        public virtual ICollection<tblGrower> tblGrowers { get; set; }
        public virtual ICollection<tblRole> tblRoles { get; set; }
    }
}
